### ISSUE TITLE
Web UI quota plugin appears to be a clone of enabled plugin

### ISSUE THREAD

**Issue by pillarama** [radiorabe/extending-freeipa#2]
Hi, Nice work on this extension. I'm not a programmer, but f I'm not mistaken it looks like the web ui plugin for quota management is code-wise identical to the Nextcloud enabled plugin with only the descriptive text and filename changed. Is that correct/intentional? I have installed this but am unable to set the quota through the webui, only enable/disable. Works fine using the CLI though.

Thanks

Pillarama

**Comment by smirta** [comment]
HI @pillarama, 

~~Did you set the quota field to "nextcloudQuota" in the Nextcloud/Owncloud configuration (Settings > User authentication > Advanced)?~~
sorry, did not read your issue well. Looks like a mistake there. I'm going to fix that and let you know. Thanks for the hint!

KR, Simon

**Comment by smirta** [comment]
https://github.com/radiorabe/freeipa-extending-ldap-schema-and-ui/commit/f6b316494227a3931604ade3de1c831db778335a should fix this. Thank you very much for that find and please let me know if it works now.

**Comment by pillarama** [comment]
Hi Simon, sorry for the slow reply - yes that seems to fix it. Thanks!

Charles
